export const Avatars = {
  1: require("../assets/avatars/01-aksel.jpeg"),
  2: require("../assets/avatars/02-chuy.jpeg"),
  3: require("../assets/avatars/03-farah.jpeg"),
  4: require("../assets/avatars/04-ghost.jpeg"),
  5: require("../assets/avatars/05-gromsko.jpeg"),
  6: require("../assets/avatars/06-gus.jpeg"),
  7: require("../assets/avatars/07-horangi.jpeg"),
  8: require("../assets/avatars/08-hutch.jpeg"),
  9: require("../assets/avatars/09-kled.jpeg"),
  10: require("../assets/avatars/10-luna.jpeg"),
  11: require("../assets/avatars/11-nova.jpeg"),
  12: require("../assets/avatars/12-oni.jpeg"),
  13: require("../assets/avatars/13-price.jpeg"),
  14: require("../assets/avatars/14-reyes.jpeg"),
  15: require("../assets/avatars/15-soap.jpeg"),
  16: require("../assets/avatars/16-stiletto.jpeg"),
  17: require("../assets/avatars/17-zimo.jpeg"),
};
